sudo: required
services:
  - docker

before_install:
  - docker build -t octavianmitu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true octavianmitu/docker-react npm run test -- --coverage